### ISSUE TITLE
New elements in the DOM

### ISSUE THREAD

**Issue by ryanmclaughlin** [goldfire/miniTip#11]
If new elements are inserted into the DOM, they don't get the miniTip binding as they should.

**Comment by goldfire** [comment]
Can you give an example of what you are trying to accomplish?

**Comment by ryanmclaughlin** [comment]
Sure. http://jsfiddle.net/mackry/RbmAz/

The Source and Status column cells have miniTips. However, when you page to a new sets of data, the miniTips no longer work. I'm assuming this is because the table is being rewritten in the DOM and the bindings don't persist for new DOM elements. 

This very well could be another issue. This was my best guess from inspection.

**Comment by goldfire** [comment]
Yes, it looks like Kendo destroys and rebuilds the entire table whenever you resort the data or change the page, which obviously destroys the event handler. I'm not familiar with Kendo, but are there no callbacks for when the table gets updated (so you could reinitialize the miniTip)?
