### ISSUE TITLE
minified version - uncaught syntax error

### ISSUE THREAD

**Issue by jasonday** [goldfire/miniTip#15]
Getting errors on the minified file. 

Chrome:
Uncaught Syntax Error: Unexpected token!

Firefox:
Timestamp: 7/16/2012 2:57:12 PM
Error: missing } after property list
Source File: https://ecwebd01.llbean.com/js/jquery.miniTip.min.js
Line: 15, Column: 183

I got better results with Closure Compiler, in comparison to uglify.js

**Comment by goldfire** [comment]
Did you pull the minified version from https://raw.github.com/goldfire/miniTip/master/jquery.miniTip.min.js? I'm not seeing any errors on any browser I've tested, do you get the same error on this fiddle?

http://jsfiddle.net/sTqyr/

**Comment by jasonday** [comment]
not seeing the error in the fiddle. I think what happened is that I used the minified file, and then our server is set to use closure compiler - so it was getting double minified, causing issues.
