### ISSUE TITLE
option for no event

### ISSUE THREAD

**Issue by ianstormtaylor** [goldfire/miniTip#21]
i'd like to show tooltips and hide them programatically. would be awesome if it didn't need an event, and i could give it a delay until it should be hidden.

**Comment by goldfire** [comment]
You can actually programmatically hide tooltips like this:

``` javascript
$('#id').miniTip({doHide: true});
```

Is this the kind of behavior you are looking for to be able to show a tooltip as well?

**Comment by ianstormtaylor** [comment]
ah. i ended up going with bootstrap tooltips because I like the `.tooltip('show')` and `.tooltip('hide')` API better  

sorry to waste your time  

—
ian storm taylor
