### ISSUE TITLE
"Sticky" Tool-Tips

### ISSUE THREAD

**Issue by influxweb** [goldfire/miniTip#7]
This is a great plugin. I have been working on making sure all my fellow developers know of it and are using it.

I am working on building a site that will be viewed on tablets only. Thankfully there is the click option for making the tip appear and I know it will disappear when you click another link that is connected to a tip or click on the original link. What I am wondering is, would it be possible to add an option to close the tip by clicking on it in addition to all the other ways currently available? The design I am working with shows an "X" on each tool tip and they are really looking forward to being able to click that to close it, but clicking anywhere on the tool top would be fine.

Cheers,
Matt

**Comment by goldfire** [comment]
Can you add a click event to the X that calls something like below to manually close the tooltip?

$('#id').miniTip({doHide: true});

**Comment by influxweb** [comment]
That didn't seem to do what I was looking for. However, I was able to make some changes that work. There may be a better way to integrate it with your code, still kind of a novice with javascript.

Replace line 38 with this:
`$('body').append('<div id="miniTip"><div id="miniTip_close">X</div><div id="miniTip_t"></div><div id="miniTip_c"></div><div id="miniTip_a"></div></div>');`

Add this at line 43:
`tt_x = $('#miniTip_close'),`

Add this at line 130:
```// clear the tooltip if the close element is clicked
tt_x.click(function (e) {
hide();
});

```

Add this at line 144:
```

// show the closing element if o.event is click
if (o.event !== 'click') {
tt_x.hide();
};

```
```

**Comment by goldfire** [comment]
Since one of the goals is keeping this as minimal as possible, I'd rather not add a standard close button into miniTip.

**Comment by influxweb** [comment]
Hi James,

I couldn't agree more about keeping the plug-in as minimal as possible. Just thought I'd share the solution that worked for me. Keep up the great work.

Cheers,
Matt

**Comment by goldfire** [comment]
Right, thank you for that, I'm sure others will find that useful as well!
