### ISSUE TITLE
Using miniTip with an image map

### ISSUE THREAD

**Issue by influxweb** [goldfire/miniTip#8]
When I try and use an image map to fire a tool tip, I am getting the following error: "num is not defined in jquery.miniTip.js line 181". I have tried using both circle and rectangular areas.

Cheers,

Matt

**Comment by goldfire** [comment]
Is there anyway you can create an example of this using http://jsfiddle.net?

**Comment by influxweb** [comment]
It looks like this issue only errors in Firefox, I am using v8.0. In Chrome and Safari, it works as expected. In IE9, it doesn't show an error but the tool tip is at the bottom of the page.

I was able to get something set up at jsFiddle. You can view the un-framed results here: http://fiddle.jshell.net/SHkSQ/6/show/light/

To view the full code, you can go here: http://jsfiddle.net/SHkSQ/6/

I am using the minified code on jsFiddle, so the error refers to "w" instead of "num".

Cheers,
Matt

**Comment by goldfire** [comment]
It appears there may be a bug in Firefox and Opera with the offset value of an image map. I'm looking into workarounds and will update when I've made progress.

**Comment by influxweb** [comment]
Hi James,

Sounds good, thank you for looking into this. I have tried figuring it out, but haven't had much luck. If I come across anything, I'll let you know.

Cheers,
Matt

**Comment by goldfire** [comment]
This is now fixed in v1.5.0, thanks!

**Comment by influxweb** [comment]
Hi James,

That's fantastic. Thank you for squashing this bug.

Cheers,
Matt

**Comment by goldfire** [comment]
Sure, thanks for pointing it out.
